# site settings
title: its computers
email: its_computers@protonmail.com
description: home to some cool stuff
baseurl: ''
url: 'https://itscomputers.github.io'

# build settings
markdown: kramdown
include:
  - _entries
  - _pages
  - _sections
kramdown:
  math_engine: mathjax
  math_engine_opts:
    preview: true
    preview_as_code: true
